[package]
name = "native-dialog"
version = "0.4.0"
authors = ["balthild <ibalthild@gmail.com>"]
edition = "2018"
description = "A library to display dialogs. Supports GNU/Linux, macOS and Windows."
license = "MIT"
documentation = "https://docs.rs/native-dialog-rs"
repository = "https://github.com/balthild/native-dialog-rs"

[dependencies]
thiserror = "1.0.19"

[target.'cfg(target_os = "windows")'.dependencies]
wfd = { git = "https://github.com/maroider/wfd", rev = "0aabdf5" }
winapi = { version = "0.3", features = ["winuser"] }
once_cell = { version = "1.4.0", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
which = "4.0.0"

[target.'cfg(target_os = "macos")'.dependencies]
osascript = "0.3.0"
serde = { version = "1.0", features = ["derive"] }

[features]
windows_dpi_awareness = []
windows_visual_styles = [
    "once_cell",
    "winapi/sysinfoapi",
    "winapi/winbase",
    "winapi/handleapi",
    "winapi/libloaderapi",
]

[workspace]
members = [
    "examples/windows_manifest",
    "examples/windows_features",
]
